webCalculator/webCalculator/Models/ErrorViewModel.cs
namespace webCalculator.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

webCalculator/webCalculator/Models/ModelsContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace webCalculator.Models
{
    public class ModelsContext : DbContext
    {
        public DbSet<ProductData> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            string databasePath = $"{AppDomain.CurrentDomain.SetupInformation.ApplicationBase}\\Data\\ProductsDatabase.db";
            options.UseSqlite(@"Data Source={databasePath}");
        }
    }
}

webCalculator/webCalculator/Models/ProductData.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webCalculator.Models;
public class ProductData
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ProdId { get; set; }

    public string? ProdTitle { get; set; }

    public string? ProdDescription { get; set; }

    public int? ProdQuantity { get; set; }

    public string? ProdBrand { get; set; }

    public string? ProdCategory { get; set; }

    public decimal? ProdPrice { get; set; }
}

webCalculator/webCalculator/Models/ProjectModels/ProductData.cs
using System;
using System.Collections.Generic;

namespace webCalculator.Models.ProjectModels;

public partial class ProductData
{
    public int ProdId { get; set; }

    public string? ProdTitle { get; set; }

    public string? ProdDescription { get; set; }

    public int? ProdQuantity { get; set; }

    public string? ProdBrand { get; set; }

    public string? ProdCategory { get; set; }

    public decimal? ProdPrice { get; set; }
}

webCalculator/webCalculator/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using webCalculator.Models;

namespace webCalculator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

webCalculator/webCalculator/Controllers/ProductsCRUDController.cs
using Microsoft.AspNetCore.Mvc;
using webCalculator.Models;

namespace webCalculator.Controllers
{
    public class ProductsCRUDController : Controller
    {


        public IActionResult DisplayProduct()
        {
            List<ProductData> products = new List<ProductData>();

            using (var db = new ModelsContext())
            {
                products = db.Products.ToList();
            }

            ViewBag.prods = products;

            return View();
        }

        public IActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddProduct(ProductData product)
        {
            using (var proddb = new ModelsContext())
            {
                proddb.Add(product);
                proddb.SaveChanges();
            }

            List<ProductData> products = new List<ProductData>();

            using (var db = new ModelsContext())
            {
                products = db.Products.ToList();
            }

            ViewBag.prods = products;
            return View();
        }
        public IActionResult UpdateProduct(ProductData product)
        {
            using (var proddb = new ModelsContext())
            {
                var TempProd = proddb.Products.Where(p => p.ProdId == product.ProdId).FirstOrDefault();
                TempData["prodTemp"] = TempProd;
            }
            return View();
        }

        public IActionResult DeleteProduct(ProductData product)
        {
            var Prod = new ProductData() { ProdId = product.ProdId} ; 
            using (var proddb = new ModelsContext())
            {
                proddb.Attach(Prod);
                proddb.Remove(Prod);
                proddb.SaveChanges();
            }
            return View("DisplayProduct");
        }

        public IActionResult UpdateProductFinal(ProductData product)
        {
            using (var proddb = new ModelsContext())
            {
                var existingProduct = proddb.Products.Where(p => p.ProdId == product.ProdId).FirstOrDefault();
                
                existingProduct.ProdTitle = product.ProdTitle;
                existingProduct.ProdDescription = product.ProdDescription;
                existingProduct.ProdQuantity = product.ProdQuantity;
                existingProduct.ProdBrand = product.ProdBrand;
                existingProduct.ProdCategory = product.ProdCategory;
                existingProduct.ProdPrice = product.ProdPrice;

                proddb.SaveChanges();
            }
            return View("DisplayProduct");
        }
    }


}

webCalculator/webCalculator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

webCalculator/webCalculator/Views/ProductsCRUD/AddProduct.cshtml
@model webCalculator.Models.ProductData
<script src="~/js/ProductCRUD.js"> </script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
@{
    ViewData["Title"] = "Add Product";

}

<h1>@ViewData["Title"]</h1>

<p>Product CRUD.</p>
<div class="text-center">
        
        <div class="form-group row" style="margin-top: 2em;">
            <label for="ProdTitle" class="col-sm-2 col-form-label" style="text-align: left;">Product Title:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="ProdTitle" name="ProdTitle" placeholder="Product Title" style="text-align: left;">
            </div>
        </div>
        <div class="form-group row" style="margin-top: 2em;">
            <label for="ProdDescription" class="col-sm-2 col-form-label" style="text-align: left;">Product Description:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="ProdDescription" name="ProdDescription" placeholder="Product Description" style="text-align: left;">
            </div>
        </div>
        <div class="form-group row" style="margin-top: 2em;">
            <label for="ProdQuantity" class="col-sm-2 col-form-label" style="text-align: left;">Product Quantity:</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="ProdQuantity" name="ProdQuantity" placeholder="Product Quantity" style="text-align: left;">
            </div>
        </div>
        <div class="form-group row" style="margin-top: 2em;">
            <label for="ProdBrand" class="col-sm-2 col-form-label" style="text-align: left;">Product Brand:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="ProdBrand" name="ProdBrand" placeholder="Product Brand" style="text-align: left;">
            </div>
        </div>
        <div class="form-group row" style="margin-top: 2em;">
            <label for="ProdCategory" class="col-sm-2 col-form-label" style="text-align: left;">Product Category:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="ProdCategory" name="ProdCategory" placeholder="Product Category" style="text-align: left;">
            </div>
        </div>
        <div class="form-group row" style="margin-top: 2em;">
            <label for="ProdPrice" class="col-sm-2 col-form-label" style="text-align: left;">Product Price:</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="ProdPrice" name="ProdPrice" placeholder="Product Price" style="text-align: left;">
            </div>
        </div>
        <div class="form-group row" style="margin-top: 2em;">
            <div class="col-sm-12 text-left">
                <button type="button" class="btn btn-primary" onclick="addProdjs()">Add Product</button>
            </div>
        </div>
</div>

webCalculator/webCalculator/Views/ProductsCRUD/DisplayProduct.cshtml
@model webCalculator.Models.ProductData
<script src="~/js/ProductCRUD.js"> </script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<link href="~/css/DisplayProduct.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "Display Products";

}

<h1>@ViewData["Title"]</h1>

   
<div class="container">
    @if(ViewBag.prods != null && ViewBag.prods.Count >0){
        <table class="table" >
            <thead>
                <tr>
                    <th>Product ID</th>  
                    <th>Product Title</th>  
                    <th>Product Description</th>  
                    <th>Product Quantity</th>  
                    <th>Product Brand</th>  
                    <th>Product Category</th>  
                    <th>Product Price</th>
                    <th>Action</th>
                </tr>  
            </thead>

            <tbody>
                @foreach(var prod in ViewBag.prods){
                    <tr>
                        <td>@prod.ProdId</td>  
                        <td>@prod.ProdTitle</td>
                        <td>@prod.ProdDescription</td>
                        <td>@prod.ProdQuantity</td>
                        <td>@prod.ProdBrand</td>
                        <td>@prod.ProdCategory</td>
                        <td>@prod.ProdPrice</td>
                        <td>
                            <div style="display: flex;">
                                <div class="Update col-sm-12">
                                    <form asp-action="UpdateProduct" asp-controller="ProductsCRUD" method="post">
                                        <input type="hidden" asp-for="ProdId" value="@prod.ProdId"/>
                                            <button type="submit" class="btn btn-primary">Update</button>
                                    </form>
                                </div>

                                <div class="delete col-sm-12">
                                    <button type="submit" class="btn btn-primary" onclick="DeleteProdjs(@prod.ProdId)">Delete</button>
                                </div>
                            </div>
                        </td>
                    </tr>  
                }
            </tbody>
           
        </table>
    }
    
</div>

webCalculator/webCalculator/Views/ProductsCRUD/UpdateProduct.cshtml
@model webCalculator.Models.ProductData
<script src="~/js/ProductCRUD.js"> </script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
@{
    ViewData["Title"] = "Update Product";
    ProductData prod = TempData["prodTemp"] as ProductData;
}

<h1>@ViewData["Title"]</h1>

<p>Product CRUD.</p>
<div class="text-center">

    <div class="form-group row" style="margin-top: 2em;">
        <label for="ProdId" class="col-sm-2 col-form-label" style="text-align: left;">Product Id:</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="ProdId" name="ProdId" placeholder="Product Id" value="@prod.ProdId" style="text-align: left;" >
        </div>
    </div>
    <div class="form-group row" style="margin-top: 2em;">
        <label for="ProdTitle" class="col-sm-2 col-form-label" style="text-align: left;">Product Title:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="ProdTitle" name="ProdTitle" placeholder="Product Title" value="@prod.ProdTitle" style="text-align: left;">
        </div>
    </div>
    <div class="form-group row" style="margin-top: 2em;">
        <label for="ProdDescription" class="col-sm-2 col-form-label" style="text-align: left;">Product Description:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="ProdDescription" name="ProdDescription" placeholder="Product Description" value="@prod.ProdDescription" style="text-align: left;">
        </div>
    </div>
    <div class="form-group row" style="margin-top: 2em;">
        <label for="ProdQuantity" class="col-sm-2 col-form-label" style="text-align: left;">Product Quantity:</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="ProdQuantity" name="ProdQuantity" placeholder="Product Quantity" value="@prod.ProdQuantity" style="text-align: left;">
        </div>
    </div>
    <div class="form-group row" style="margin-top: 2em;">
        <label for="ProdBrand" class="col-sm-2 col-form-label" style="text-align: left;">Product Brand:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="ProdBrand" name="ProdBrand" placeholder="Product Brand" value="@prod.ProdBrand" style="text-align: left;">
        </div>
    </div>
    <div class="form-group row" style="margin-top: 2em;">
        <label for="ProdCategory" class="col-sm-2 col-form-label" style="text-align: left;">Product Category:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="ProdCategory" name="ProdCategory" placeholder="Product Category" value="@prod.ProdCategory" style="text-align: left;">
        </div>
    </div>
    <div class="form-group row" style="margin-top: 2em;">
        <label for="ProdPrice" class="col-sm-2 col-form-label" style="text-align: left;">Product Price:</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="ProdPrice" name="ProdPrice" placeholder="Product Price" value="@prod.ProdPrice" style="text-align: left;">
        </div>
    </div>
    <div class="form-group row" style="margin-top: 2em;">
        <div class="col-sm-12 text-left">
            <button type="button" class="btn btn-primary" onclick="updateProdjs()">Update Product</button>
        </div>
    </div>
</div>

webCalculator/webCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webCalculator.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webCalculator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsCRUD" asp-action="DisplayProduct">Display Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsCRUD" asp-action="AddProduct">Add Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - webCalculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>